apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fleetman
  namespace: default
spec:
  rules:
    - host: fleetman.com
      http:
        paths:
          - backend:
              service:
                name: fleetman-webapp
                port:
                  number: 80
            path: /
            pathType: Prefix
