
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  {{- include "webapp-replicas" . | indent 2 -}}
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      {{- include "webapp" . | indent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort
